package online.expensage.android.ui.theme

import androidx.compose.ui.graphics.Color

// Brand tokens shared with the web app (src/styles/tailwind.css)
val ExpenSageGreen = Color(0xFF006049)
val ExpenSageGreenStrong = Color(0xFF004F3D)
val ExpenSageInk = Color(0xFF10211C)
val ExpenSageMuted = Color(0xFF5D7069)
val ExpenSageCanvas = Color(0xFFF6FBF9)
val ExpenSageLine = Color(0xFFD7E8E3)
val ExpenSageWarning = Color(0xFFF59E0B)
val ExpenSageDanger = Color(0xFFDC2626)

// Light
val primaryLight = Color(0xFF006049)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE1EFEA)
val onPrimaryContainerLight = Color(0xFF004F3D)
val secondaryLight = Color(0xFF5D7069)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE6F1EC)
val onSecondaryContainerLight = Color(0xFF344C42)
val tertiaryLight = Color(0xFF4C6359)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE1EFEA)
val onTertiaryContainerLight = Color(0xFF264B5D)
val errorLight = Color(0xFFDC2626)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFEE2E2)
val onErrorContainerLight = Color(0xFF7F1D1D)
val backgroundLight = Color(0xFFF6FBF9)
val onBackgroundLight = Color(0xFF10211C)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF10211C)
val surfaceVariantLight = Color(0xFFEEF7F4)
val onSurfaceVariantLight = Color(0xFF5D7069)
val outlineLight = Color(0xFF9BB5AD)
val outlineVariantLight = Color(0xFFD7E8E3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322F)
val inverseOnSurfaceLight = Color(0xFFECF2ED)
val inversePrimaryLight = Color(0xFF7FD8BC)
val surfaceDimLight = Color(0xFFDCE7E2)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6FBF9)
val surfaceContainerLight = Color(0xFFEEF7F4)
val surfaceContainerHighLight = Color(0xFFE6F1EC)
val surfaceContainerHighestLight = Color(0xFFDDEAE4)

// Dark
val primaryDark = Color(0xFF7FD8BC)
val onPrimaryDark = Color(0xFF003828)
val primaryContainerDark = Color(0xFF00513D)
val onPrimaryContainerDark = Color(0xFFA5F2D4)
val secondaryDark = Color(0xFFB2CCC0)
val onSecondaryDark = Color(0xFF1E352C)
val secondaryContainerDark = Color(0xFF344C42)
val onSecondaryContainerDark = Color(0xFFCEE9DC)
val tertiaryDark = Color(0xFFA7CCE1)
val onTertiaryDark = Color(0xFF0B3445)
val tertiaryContainerDark = Color(0xFF264B5D)
val onTertiaryContainerDark = Color(0xFFC3E8FE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1512)
val onBackgroundDark = Color(0xFFE6EFEA)
val surfaceDark = Color(0xFF121A16)
val onSurfaceDark = Color(0xFFE6EFEA)
val surfaceVariantDark = Color(0xFF1E2A25)
val onSurfaceVariantDark = Color(0xFFB9C9C2)
val outlineDark = Color(0xFF89938D)
val outlineVariantDark = Color(0xFF34443D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6EFEA)
val inverseOnSurfaceDark = Color(0xFF2C322F)
val inversePrimaryDark = Color(0xFF006049)
val surfaceDimDark = Color(0xFF0F1512)
val surfaceBrightDark = Color(0xFF343B37)
val surfaceContainerLowestDark = Color(0xFF0A0F0D)
val surfaceContainerLowDark = Color(0xFF121A16)
val surfaceContainerDark = Color(0xFF1B211E)
val surfaceContainerHighDark = Color(0xFF252B28)
val surfaceContainerHighestDark = Color(0xFF303633)
